### ISSUE TITLE
Broken build against msgpack 1.3.0

### ISSUE THREAD

**Issue by remicollet** [alphashack/graphdat-sdk-php#8]
Buildtime:

```
 warning: implicit declaration of function 'msgpack_pack_raw' [-Wimplicit-function-declaration]
 warning: implicit declaration of function 'msgpack_pack_raw_body' [-Wimplicit-function-declaration]
```

Runtime

```
 PHP Warning:  PHP Startup: Unable to load dynamic library '..../modules/graphdat.so' - ..../modules/graphdat.so: undefined symbol: msgpack_pack_raw_body in Unknown on line 0
```

**Comment by hilyjiang** [comment]
I encounter this issue as well under CentOS 7, is there any patch for it?

**Comment by codemoran** [comment]
Hi @remicollet / @hilyjiang 

My apologies on the delay.  The application monitoring features are no longer part of the product, [BMC TrueSight Pulse](bmc.com/pulse), and the modules have been deprecated when the product was transitioned from Boundary Premium to BMC TrueSight Pulse.

This was announced in a couple of the monthly emails and a notification within the application, but the modules were left in their repos so we would not break anyones builds.

Again, my apologies on being late to this message.
